DROP DATABASE NOTIFYTEC;

CREATE DATABASE IF NOT EXISTS NOTIFYTEC;

USE NOTIFYTEC;

CREATE TABLE IF NOT EXISTS SEMESTRE(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  INICIO DATE,
  FIM DATE
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  NOME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CURSO(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  NOME VARCHAR(100),
  APELIDO VARCHAR(30),
  ATIVO BOOLEAN
);

CREATE TABLE IF NOT EXISTS PERIODO(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  NUMERO INT,
  CURSOID BINARY(16),
  FOREIGN KEY (CURSOID) REFERENCES CURSO(ID)
);

CREATE TABLE IF NOT EXISTS USUARIO(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  LOGIN VARCHAR(50),
  SENHA VARCHAR(60),
  PODEENVIAR BOOLEAN,
  ALTEROUSENHA BOOLEAN,
  EMAIL VARCHAR(100),
  TOKENRECUPERARSENHA VARCHAR(5),
  DATAVALIDADETOKEN DATETIME
);


CREATE TABLE IF NOT EXISTS PESSOA(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  NOME VARCHAR(100),
  SOBRENOME VARCHAR(100),
  APELIDO VARCHAR(50),
  CPF VARCHAR(15),
  USUARIOID BINARY(16),
  FOREIGN KEY (USUARIOID) REFERENCES USUARIO(ID),
  DEPARTAMENTOID BINARY(16),
  FOREIGN KEY (DEPARTAMENTOID) REFERENCES DEPARTAMENTO(ID),
  ATIVO BOOLEAN
);


CREATE TABLE IF NOT EXISTS ALUNO(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  NOME VARCHAR(100),
  SOBRENOME VARCHAR(100),
  RA VARCHAR(12),
  CPF VARCHAR(15),
  USUARIOID BINARY(16),
  FOREIGN KEY (USUARIOID) REFERENCES USUARIO(ID),
  ATIVO BOOLEAN
);

CREATE TABLE IF NOT EXISTS ALUNOPERIODO(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  ALUNOID BINARY(16),
  FOREIGN KEY (ALUNOID) REFERENCES ALUNO(ID),
  PERIODOID BINARY(16),
  FOREIGN KEY (PERIODOID) REFERENCES PERIODO(ID),
  INICIO DATE,
  FIM DATE,
  SEMESTREID BINARY(16),
  FOREIGN KEY (SEMESTREID) REFERENCES SEMESTRE(ID)
);

CREATE TABLE IF NOT EXISTS NOTIFICACAO(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  TITULO VARCHAR(100),
  CONTEUDO TEXT,
  ENQUETE BOOLEAN,
  EXPIRAEM DATETIME,
  USUARIOID BINARY(16),
  FOREIGN KEY (USUARIOID) REFERENCES USUARIO(ID),
  DATAHORAENVIO DATETIME
);

CREATE TABLE IF NOT EXISTS NOTIFICACAOOPCAO(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  NOTIFICAOID BINARY(16),
  FOREIGN KEY (NOTIFICAOID) REFERENCES NOTIFICACAO(ID),
  NOME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ALUNONOTIFICACAO(
  ID BINARY(16) PRIMARY KEY NOT NULL,
  NOTIFICACAOID BINARY(16),
  FOREIGN KEY (NOTIFICACAOID) REFERENCES NOTIFICACAO(ID),
  ALUNOID BINARY(16),
  FOREIGN KEY (ALUNOID) REFERENCES ALUNO(ID),
  VIZUALIZOUEM DATETIME,
  NOTIFICACAOOPCAOID BINARY(16),
  FOREIGN KEY (NOTIFICACAOOPCAOID) REFERENCES NOTIFICACAOOPCAO(ID)
);

/* USUARIOS COM SENHA = "senha" */
INSERT INTO USUARIO VALUES (UNHEX('1851a48b273847c9b9d11a31ca8b602b'), 'aluno', 'e8d95a51f3af4a3b134bf6bb680a213a', 0, 1, 'login@login.com', NULL, NULL);
INSERT INTO USUARIO VALUES (UNHEX('475c9bf7055b47deaf8c7524d4cde316'), 'professor', 'e8d95a51f3af4a3b134bf6bb680a213a', 1, 1, 'login@login.com', NULL, NULL);

INSERT INTO DEPARTAMENTO VALUES (UNHEX('06e81da62bd34cdc8f728ae460cc7706'), 'Administração');

/*CADASTRO DE UM PROFESSOR*/
INSERT INTO PESSOA VALUES (UNHEX('85c6a979c1a64064bc35758442216dab'), 'Luix Fernandox', 'Santox', 'Luixx', '123.234.445-09', UNHEX('475c9bf7055b47deaf8c7524d4cde316'), UNHEX('06e81da62bd34cdc8f728ae460cc7706'), 1);